#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jun 10 13:18:06 +07 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 99bb8ba48af54c3584218e26f5b51b7f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_qlue_cisc_behav xil_defaultlib.tb_qlue_cisc xil_defaultlib.glbl -log elaborate.log"
xelab -wto 99bb8ba48af54c3584218e26f5b51b7f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_qlue_cisc_behav xil_defaultlib.tb_qlue_cisc xil_defaultlib.glbl -log elaborate.log

